Makefile
README.md

The `docker_shell ` command of `salt-toaster` binds port `4444` by default for rpdb debugging. This causes that several `docker_shell` cannot run at the same time.
This PR introduces the use of `RPDB_PORT` env variable in order to bind the rpdb to certain port only when this env variable is used.

Using RPDB_PORT env variable instead of binding rpdb port as default

---

conftest.py.source

This PR fixes tests execution for `products-next`:
1. Adds missing `python-backports.ssl_match_hostname` package which is not autoinstalled in SLES11 versions.
2. Upgrades and patches `salttesting` to support old `python-psutil` versions. We're currently shipping `python-psutil` version 1.2.1. Upstream `salttesting` fixes this issue but it's not released yet so manual patch is applied to the upgraded `salttesting`.
3. Sets initial xfail and ignore list for integration tests.
This changes should fix the issues which causes failures during `products-next` tests execution.

Fixing tests execution for version 2016.11.1 (products-next)

---

utils.py

This is needed to invalidate cache for steps after `ARG CACHE_DATE=nocache` in the Dockerfile, as currently unwanted steps are been cached.

Allows invalidate cache for certains Dockerfile steps

---

Makefile

we will benifts for more sorting and  benifits for toaster.
Jenkins will give more meta-info about junit
for users we don't have any changes 
@meaksh @dincamihai @brejoc 
I think we can change 'results.xml' to 'toaster_results.xml' or open for other names :rabbit: :smile:

Add junit support

---

Makefile
README.adoc

The Makefile now takes two additional parameters: DOCKER_MEM and DOCKER_CPUS
DOCKER_MEM allows to limit the available memory usage.
https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory
DOCKER_CPUS limits the CPU resources a container can use.
https://docs.docker.com/config/containers/resource_constraints/#cpu

Adds resource limits for Docker run

---

reports/.gitignore
tests/conftest.py

This PR creates a cProfile containing all stats from the pytest execution. 
- Store the full cProfile profile into `reports/global.prof` file after pytest execution.
- Save "accumulated" values from previous runs on `reports/toaster-timings.json`.
- Export metrics to Prometheus via node exporter: `/var/lib/node_exporter/textfile_collector/salt_toaster.prom`
Current calculated metrics are (exported as accumulated values):
- "pytest_runtest_setup" -- Tests preparation time (fixtures, creating containers, etc).
- "pytest_runtest_call" -- Actual tests execution time.
- "pytest_runtest_teardown" -- Tests teardown time (cleaning up, removing containers, etc).

Create cProfile from pytest execution and export metrics to Prometheus node exporter

---

Makefile
configs/saltstack.integration/sles15.cfg
configs/saltstack.unit/sles15.cfg
configs/suse.tests/sles15/products-next.cfg
configs/suse.tests/sles15/unstable.cfg

This PR fixes the salt-toaster issues after reverting https://github.com/openSUSE/salt-toaster/commit/29a1155472e0782308bc26f385cf25f789420d96 (which was reverted because pytest on python2.6 systems doesn't accept the new `[tool:pytest]` header).
So, this PR set a SLE15 specific configuration file to use the new header format and to keep the old format for older systems.
/cc @dincamihai

Use a SLES15 specific pytest configuration file

---

conftest.py.source

The `integration/__init__.py` file was added to the ignore_list back in 2017 (for "products-next") but now this is causing an issue when running `pytest` that produces no tests are collected on SLE15:
```
timeout 180m pytest -c ./configs/saltstack.integration/sles15.cfg /salt/src/salt-*/tests  --timeout=500 --junitxml results.xml
============================= test session starts ==============================
platform linux -- Python 3.6.5, pytest-3.9.2, py-1.5.3, pluggy-0.8.0 -- /usr/bin/python3
cachedir: .pytest_cache
tempdir: /tmp/salt-toaster
rootdir: /salt/src/salt-2018.3.0/tests, inifile: ./configs/saltstack.integration/sles15.cfg
plugins: timeout-1.3.2, tempdir-2016.8.20, salt-2018.9.28, helpers-namespace-2017.11.11, catchlog-1.2.2
timeout: 500.0s
timeout method: signal
timeout …
```

Do not exclude 'integration/__init__.py' so tests can run on SLE15

---

conftest.py.source

This test is currently failing on `2016.11.10` because the release tarball
is broken and it does not contain the expected symlink on the `file_roots`.

Add 'RootsTest::test_symlink_list' to xfailed for SLE11 and RHEL6

---

tests/test_components.py

After latest update of pytest to 4.0.0 we're reaching errors [1] during `suse.tests` execution because `getfuncargvalue` function has been deprecated:
https://ci.suse.de/user/manager/my-views/view/Salt/view/default/job/manager-products-old-testing-suse-integration-sles11sp4/341/console
This PR makes use of the suggested alternative: `getfixturevalue` to make tests works.

Prevent failure on pytest 4.0.0 because getfuncargvalue deprecation

---

Makefile

With a fresh installation there is no env. variable for `ST_JOB_ID` and we get a misleading error from Docker that `--label` cannot be empty.
By default `ST_JOB_ID` is now set to 'local-test-run' if nothing else is provided.
Closes  #75

Provide default for ST_JOB_ID

---

README.adoc
README_SUSE.adoc

For Python3 systems the packages need to be different and Tumbleweeds seems to accept the cert in a different place.

Added Python3 details and cert path for TW

---

README.adoc

We don't need instructions for both Python2 and Python3 for openSUSE
systems, all openSUSE distros come with Python3.

Drop Python2 instructions for openSUSE

---

conftest_source.py

This is for making the test suite green so we can start from green and
then fix the issues.
More at https://github.com/SUSE/spacewalk/issues/14284
Signed-off-by: Jordi Massaguer Pla <jmassaguerpla@suse.de>

Force new "green start" for integration tests

---

conftest_source.py

This is so we can do a "new green start" so that we can run this on Pull
Requests to prevent merges that break existing tests that succeed. Thus,
we are ignoring the ones that fail right now.
Signed-off-by: Jordi Massaguer Pla <jmassaguerpla@suse.de>

Update "xfail" tests to ignore failures on known issues for **Ubuntu**

---

conftest_source.py

This test was ignored anyway for the last release.
Signed-off-by: Jordi Massaguer Pla <jmassaguerpla@suse.de>

Make ubuntu 16.04 green

---

conftest_source_legacy.py

We run the Salt Toaster in GH Actions in openSUSE Leap docker containers. There are currently some failures in Salt 3000's toaster unit test runs that don't happen in SLE because we skip the tests in SLE. These changes align Leap with SLE.

Update ignores/xfails for legacy_toaster in Leap

---

Makefile
bin/install_salt_sources.sh
configs/suse.tests/leap15.4/products-testing.cfg
configs/suse.tests/leap15.4/products.cfg
images/templates/leap.jinja
images/templates/leap15.4.jinja
images/utils.py
tests/common.py
tests/test_pkg_list_products.py

This image template is used for Leap 15.4 and SLES 15SP4, which use the same repo anyway (closing the leap gap!).
I tested the template with `IMAGE_REGISTRY=registry.opensuse.org`, once I pushed the official Leap 15.4 to our internal registry, template generation won't need to set that environment variable.

Add Template for Leap 15.4 / SLES 15 SP4

---

Makefile
conftest_source_nox.py

This PR makes Salt Toaster to generate `_version.txt` file when `FLAVOR=devel` is set, in order to fix the Salt version before starting test execution.
For non-devel flavors, the version is set (and file already generated) at the time of building the package, but this is not the case when using toaster against a git repository.
Additionally, this PR removes some ignored salt support tests from the ignored list, as they are passing now.

Generate "_version.txt" file with fixed Salt version when flavor is "devel"

---

conftest_source_nox.py

This PR removes some working tests from Salt Toaster ignored tests, as they are now fixed by: https://github.com/openSUSE/salt/pull/580

Remove working and passing "salt-support" tests from ignored list
